export const skillList = [
  {id: 'Marketing', name: 'Marketing'},
  {id: 'Content Writing', name: 'Content Writing'},
  {id: 'SEO', name: 'SEO'},
  {id: 'Community', name: 'Community'},
  {id: 'Social Media', name: 'Social Media'},
  {id: 'Front-End Dev', name: 'Front-End Dev'},
  {id: 'Back-End Dev', name: 'Back-End Dev'},
  {id: 'Full-Stack Dev', name: 'Full-Stack Dev'},
  {id: 'Web Design', name: 'Web Design'},
  {id: 'ThreeJS', name: 'ThreeJS'},
  {id: 'React', name: 'React'},
  {id: 'NodeJS', name: 'NodeJS'},
  {id: 'AWS', name: 'AWS'},
  {id: 'Solidity', name: 'Solidity'},
  {id: 'Rust', name: 'Rust'},
  {id: 'Hardhat', name: 'Hardhat'},
  {id: 'Truffle', name: 'Truffle'},
  {id: 'EtherJS', name: 'EtherJS'},
  {id: 'Web3', name: 'Web3'},
  {id: 'VR/AR', name: 'VR/AR'},
  {id: 'UI/UX', name: 'UI/UX'},
  {id: 'Game Design', name: 'Game Design'},
  {id: 'Game Dev', name: 'Game Dev'},
  {id: 'Unreal', name: 'Unreal'},
  {id: 'Unity', name: 'Unity'}
]
