import Head from 'next/head'
import Image from 'next/image'
import Navbar from './navigation/Navbar';
import Landing from './landing/Landing';

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Job Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/DeveloperDaoFavicon.ico" />
      </Head>
      <Navbar/>
      <Landing/>
      <h1>This is a job board</h1>
    </div>
  )
}
