import Landing from '../components/Landing';
import Head from 'next/head';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Navbar from '../components/navigation/Navbar';

export default function Home() {
  const { t } = useTranslation('common');
  return (
    <div>
      <Head>
        <title>{t('common.title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/DeveloperDaoFavicon.ico" />
      </Head>
      <Landing />
    </div>
  );
}

export const getStaticProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
});
